services:
  frontend:
    container_name: wedding_frontend
    platform: linux/arm64
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - wedding_network
    ports:
      - "3000:3000"

  backend:
    container_name: wedding_backend
    platform: linux/arm64
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - wedding_network
    ports:
      - "3000:3000"
    privileged: true
    volumes:
      - /var/run/cups:/var/run/cups:ro
      - /dev/bus/usb:/dev/bus/usb:ro    # 访问USB设备（如果打印机是USB连接）
    environment:
      - CUPS_SERVER=localhost:631

